spring:
  jpa:
    hibernate:
      ddl-auto: update
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DEV_DB_NAME}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  application:
  name: vpnbot
bot:
  token: ${vpn_bot_token}

server:
  host: ${DEV_SERVER_HOST}
  password: ${DEV_SERVER_PASSWORD}
  public_key: ${DEV_SERVER_PUBLIC_KEY}
  private_key: ${DEV_SERVER_PRIVATE_KEY}
